@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzU0NjE3MjJ9.QLk6HG6OfxV9DYoCX-mHPVuqpIvZJ_ScULSx7gwbw-w

### Users Show (Tested)
GET http://localhost:3000/users/me
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Users Update (Tested)
PATCH http://localhost:3000/users/me
Authorization: Bearer {{jwt}}
Content-Type: application/json

  {
    "name": "Test_user_Change", 
    "email": "test2@test.com",
    "password": "password"
  }

### User Create (Tested)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "test5",
  "email": "test5@test.com",
  "password": "password",
  "password_confirmation": "password" 
}

### User Destroy (Tested)
DELETE http://localhost:3000/users/me
Authorization: Bearer {{jwt}}

### Sessions Create (Tested)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "natelalvarado@gmail.com",
  "password": "temppassword" 
}

### Media Index(Tested)
GET http://localhost:3000/media
Authorization: Bearer {{jwt}}

### Media Show (Tested)
GET http://localhost:3000/media/1
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Media Create (Tested)
POST http://localhost:3000/media
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "media_type": "test",
  "title": "Test name",
  "creator": "Test",
  "genre": "Test" ,
  "year": "test" ,
  "image": "test", 
  "review": "test",
  "rating": "test" ,
  "status": "test" ,
  "cast": "test" ,
  "plot": "test" 
}

### Media Update (Tested)
PATCH http://localhost:3000/media/6
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "media_type": "Movie",
  "title": "Test name",
  "creator": "Test",
  "genre": "Test" ,
  "year": "test" ,
  "image": "test", 
  "review": "test",
  "rating": "test" ,
  "status": "test" ,
  "cast": "test" ,
  "plot": "test" 
}

### Media Destroy (Tested)
DELETE http://localhost:3000/media/6
Authorization: Bearer {{jwt}}